In [1]:
import pandas as pd
import sqlite3
import os

project_path = os.path.join(os.path.expanduser("~"), "Documents", "Healthcare_SQL_Analytics")

data_path = os.path.join(
    project_path,
    "data",
    "hospital_readmissions.csv"
)

db_path = os.path.join(
    project_path,
    "healthcare_readmissions.db"
)

print("Project path:", project_path)
print("Data path:", data_path)
print("Database path:", db_path)

print("\nData file exists:", os.path.exists(data_path))

Project path: C:\Users\lbona\Documents\Healthcare_SQL_Analytics
Data path: C:\Users\lbona\Documents\Healthcare_SQL_Analytics\data\hospital_readmissions.csv
Database path: C:\Users\lbona\Documents\Healthcare_SQL_Analytics\healthcare_readmissions.db

Data file exists: True

In [4]:
df = pd.read_csv(data_path)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Rows: 25000
Columns: 17
Column names:
['age', 'time_in_hospital', 'n_lab_procedures', 'n_procedures', 'n_medications', 'n_outpatient', 'n_inpatient', 'n_emergency', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'glucose_test', 'A1Ctest', 'change', 'diabetes_med', 'readmitted']

Data types:
age                  object
time_in_hospital      int64
n_lab_procedures      int64
n_procedures          int64
n_medications         int64
n_outpatient          int64
n_inpatient           int64
n_emergency           int64
medical_specialty    object
diag_1               object
diag_2               object
diag_3               object
glucose_test         object
A1Ctest              object
change               object
diabetes_med         object
readmitted           object
dtype: object

Missing values:
age                  0
time_in_hospital     0
n_lab_procedures     0
n_procedures         0
n_medications        0
n_outpatient         0
n_inpatient          0
n_emergency          0
medical_specialty    0
diag_1               0
diag_2               0
diag_3               0
glucose_test         0
A1Ctest              0
change               0
diabetes_med         0
readmitted           0
dtype: int64

In [5]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- age ---
age
[70-80)     6837
[60-70)     5913
[80-90)     4516
[50-60)     4452
[40-50)     2532
[90-100)     750
Name: count, dtype: int64

--- medical_specialty ---
medical_specialty
Missing                   12382
InternalMedicine           3565
Other                      2664
Emergency/Trauma           1885
Family/GeneralPractice     1882
Cardiology                 1409
Surgery                    1213
Name: count, dtype: int64

--- diag_1 ---
diag_1
Circulatory        7824
Other              6498
Respiratory        3680
Digestive          2329
Diabetes           1747
Injury             1666
Musculoskeletal    1252
Missing               4
Name: count, dtype: int64

--- diag_2 ---
diag_2
Other              9056
Circulatory        8134
Diabetes           2906
Respiratory        2872
Digestive           973
Injury              591
Musculoskeletal     426
Missing              42
Name: count, dtype: int64

--- diag_3 ---
diag_3
Other              9107
Circulatory        7686
Diabetes           4261
Respiratory        1915
Digestive           916
Injury              464
Musculoskeletal     455
Missing             196
Name: count, dtype: int64

--- glucose_test ---
glucose_test
no        23625
normal      689
high        686
Name: count, dtype: int64

--- A1Ctest ---
A1Ctest
no        20938
high       2827
normal     1235
Name: count, dtype: int64

--- change ---
change
no     13497
yes    11503
Name: count, dtype: int64

--- diabetes_med ---
diabetes_med
yes    19228
no      5772
Name: count, dtype: int64

--- readmitted ---
readmitted
no     13246
yes    11754
Name: count, dtype: int64

In [6]:
print(df["readmitted"].value_counts())

print("\nReadmission Rate:")
print(round(df["readmitted"].value_counts(normalize=True) * 100, 2))

readmitted
no     13246
yes    11754
Name: count, dtype: int64

Readmission Rate:
readmitted
no     52.98
yes    47.02
Name: proportion, dtype: float64

In [7]:
pd.crosstab(
    df["change"],
    df["readmitted"],
    normalize="index"
) * 100

readmitted         no        yes
change
no          54.975180  45.024820
yes         50.647657  49.352343

In [8]:
df.groupby("readmitted")["n_inpatient"].mean()

readmitted
no     0.380190
yes    0.881657
Name: n_inpatient, dtype: float64

In [9]:
df.groupby("readmitted")["n_emergency"].mean()

readmitted
no     0.108561
yes    0.274545
Name: n_emergency, dtype: float64

In [10]:
df.groupby("readmitted")["time_in_hospital"].mean()

readmitted
no     4.331345
yes    4.590778
Name: time_in_hospital, dtype: float64

In [11]:
pd.crosstab(
    df["A1Ctest"],
    df["readmitted"],
    normalize="index"
) * 100

readmitted         no        yes
A1Ctest
high        54.050230  45.949770
no          52.550387  47.449613
normal      57.894737  42.105263

In [12]:
pd.crosstab(
    df["diabetes_med"],
    df["readmitted"],
    normalize="index"
) * 100

readmitted           no        yes
diabetes_med
no            58.645184  41.354816
yes           51.284585  48.715415